package pe.edu.unsch.entities;
// Generated 28/06/2019 07:34:05 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name = "Docente", catalog = "cargabd")
public class Docente implements java.io.Serializable {

	private int idDocente;
	private String nombreDocente;
	private String apellidoDocente;
	private Set<Semestre> semestres = new HashSet<Semestre>(0);

	public Docente() {
	}

	public Docente(int idDocente, String nombreDocente, String apellidoDocente) {
		this.idDocente = idDocente;
		this.nombreDocente = nombreDocente;
		this.apellidoDocente = apellidoDocente;
	}

	public Docente(int idDocente, String nombreDocente, String apellidoDocente, Set<Semestre> semestres) {
		this.idDocente = idDocente;
		this.nombreDocente = nombreDocente;
		this.apellidoDocente = apellidoDocente;
		this.semestres = semestres;
	}

	@Id

	@Column(name = "idDocente", unique = true, nullable = false)
	public int getIdDocente() {
		return this.idDocente;
	}

	public void setIdDocente(int idDocente) {
		this.idDocente = idDocente;
	}

	@Column(name = "NombreDocente", nullable = false, length = 50)
	public String getNombreDocente() {
		return this.nombreDocente;
	}

	public void setNombreDocente(String nombreDocente) {
		this.nombreDocente = nombreDocente;
	}

	@Column(name = "ApellidoDocente", nullable = false, length = 50)
	public String getApellidoDocente() {
		return this.apellidoDocente;
	}

	public void setApellidoDocente(String apellidoDocente) {
		this.apellidoDocente = apellidoDocente;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docente")
	public Set<Semestre> getSemestres() {
		return this.semestres;
	}

	public void setSemestres(Set<Semestre> semestres) {
		this.semestres = semestres;
	}

}
