package pe.edu.unsch.entities;
// Generated 05/07/2019 02:09:15 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Semestre generated by hbm2java
 */
@Entity
@Table(name = "semestre", catalog = "cargabd")
public class Semestre implements java.io.Serializable {

	private int idSemestre;
	private Docente docente;
	private String semestreAcademico;
	private int cargaAcademica;

	public Semestre() {
	}

	public Semestre(int idSemestre, Docente docente, String semestreAcademico, int cargaAcademica) {
		this.idSemestre = idSemestre;
		this.docente = docente;
		this.semestreAcademico = semestreAcademico;
		this.cargaAcademica = cargaAcademica;
	}

	@Id

	@Column(name = "id_semestre", unique = true, nullable = false)
	public int getIdSemestre() {
		return this.idSemestre;
	}

	public void setIdSemestre(int idSemestre) {
		this.idSemestre = idSemestre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "docente_id_docente", nullable = false)
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@Column(name = "semestre_academico", nullable = false, length = 50)
	public String getSemestreAcademico() {
		return this.semestreAcademico;
	}

	public void setSemestreAcademico(String semestreAcademico) {
		this.semestreAcademico = semestreAcademico;
	}

	@Column(name = "carga_academica", nullable = false)
	public int getCargaAcademica() {
		return this.cargaAcademica;
	}

	public void setCargaAcademica(int cargaAcademica) {
		this.cargaAcademica = cargaAcademica;
	}

}
